Repository BrightCoders-Institute/proyecto-final-jdg, pull requests merged in 2023-08, with the labels that each got.

#8 Generated login
  Gemfile
  Gemfile.lock
  app/models/admin.rb
  app/models/customer.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20230801013530_devise_create_users.rb
  db/migrate/20230801014426_add_first_name_to_users.rb
  db/migrate/20230801014445_add_last_name_to_users.rb
  db/migrate/20230801025745_add_user_type_to_users.rb
  db/schema.rb
  test/fixtures/admins.yml
  test/fixtures/customers.yml
  test/fixtures/users.yml
  test/models/admin_test.rb
  test/models/customer_test.rb
  test/models/user_test.rb
Labels: WIP

#9 Now mailer works properly with encripted credentials
  app/models/user.rb
  config/credentials.yml.enc
  config/environments/development.rb
  db/migrate/20230801232645_add_confirmable_to_user.rb
  db/schema.rb
Labels: review required

#13 CRUD for user addresses added
  app/controllers/addresses_controller.rb
  app/helpers/addresses_helper.rb
  app/models/address.rb
  app/models/user.rb
  app/views/addresses/_form.html.erb
  app/views/addresses/edit.html.erb
  app/views/addresses/index.html.erb
  app/views/addresses/new.html.erb
  config/routes.rb
  db/migrate/20230803005435_create_addresses.rb
  db/migrate/20230803010116_add_user_to_address.rb
  db/schema.rb
  test/controllers/addresses_controller_test.rb
  test/fixtures/addresses.yml
  test/models/address_test.rb
Labels: review required

#12 Navbar and footer
  Gemfile
  Gemfile.lock
  app/assets/images/monkeyHats.webp
  app/assets/stylesheets/application.css
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_top-message.scss
  app/assets/stylesheets/config/variables.scss
  app/assets/stylesheets/layout/_footer.scss
  app/assets/stylesheets/layout/_header.scss
  app/assets/stylesheets/layout/_navbar.scss
  app/controllers/home_controller.rb
  app/javascript/application.js
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/partials/components/_top-message.html.erb
  app/views/partials/layout/_footer.html.erb
  app/views/partials/layout/_navbar.html.erb
  config/importmap.rb
  config/initializers/assets.rb
  config/routes.rb
  test/controllers/home_controller_test.rb
Labels: review required

#10 Users validations and tests
  app/models/user.rb
  app/views/devise/shared/_error_messages.html.erb
  test/fixtures/admins.yml
  test/fixtures/customers.yml
  test/fixtures/users.yml
  test/models/user_test.rb
Labels: review required

#16 Style views devise
  Gemfile
  app/assets/images/edit-user-img.png
  app/assets/images/login-image.webp
  app/assets/images/password-img.jpg
  app/assets/images/registration-img.jpg
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/links.scss
  app/assets/stylesheets/components/login.scss
  app/assets/stylesheets/components/passwords.scss
  app/assets/stylesheets/components/registrations.scss
  app/assets/stylesheets/config/variables.scss
  app/javascript/application.js
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
Labels: review required

#22 Registration Form Validation Issue
  app/assets/images/edit-user-img.png
  app/assets/images/edit-user-img.webp
  app/assets/images/password-img.jpg
  app/assets/images/password-img.webp
  app/assets/images/registration-img.jpg
  app/assets/images/registration-img.webp
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/login.scss
  app/assets/stylesheets/components/top-message.scss
  app/assets/stylesheets/layout/_footer.scss
  app/assets/stylesheets/layout/_header.scss
  app/controllers/addresses_controller.rb
  app/controllers/application_controller.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/partials/layout/_navbar.html.erb
Labels: review required

#25 CRUD PRODUCTS
  Gemfile.lock
  app/controllers/addresses_controller.rb
  app/controllers/application_controller.rb
  app/controllers/products_controller.rb
  app/helpers/products_helper.rb
  app/models/product.rb
  app/views/partials/layout/_navbar.html.erb
  app/views/products/_form.html.erb
  app/views/products/_product.html.erb
  app/views/products/_product.json.jbuilder
  app/views/products/edit.html.erb
  app/views/products/index.html.erb
  app/views/products/index.json.jbuilder
  app/views/products/new.html.erb
  app/views/products/show.html.erb
  app/views/products/show.json.jbuilder
  config/routes.rb
  db/migrate/20230810065504_create_products.rb
  db/migrate/20230810071220_create_active_storage_tables.active_storage.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/products_controller_test.rb
  test/fixtures/products.yml
  test/models/product_test.rb
  test/system/products_test.rb
Labels: review required

#24 Merge Styles for Confirmation Email View
  app/assets/images/confirmation.webp
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/confirmation.scss
  app/assets/stylesheets/components/passwords.scss
  app/assets/stylesheets/components/registrations.scss
  app/views/addresses/_form.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/partials/layout/_footer.html.erb
Labels: review required

#27 Styles for edit, delete, and display user directions views
  app/views/addresses/_form.html.erb
  app/views/addresses/edit.html.erb
  app/views/addresses/index.html.erb
  app/views/addresses/new.html.erb
Labels: review required

#26 Admin panel
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/buttons.scss
  app/assets/stylesheets/components/links.scss
  app/views/products/_form.html.erb
  app/views/products/_product.html.erb
  app/views/products/edit.html.erb
  app/views/products/index.html.erb
  app/views/products/new.html.erb
  app/views/products/show.html.erb
Labels: review required

#31 Generate shopping cart
  app/controllers/addresses_controller.rb
  app/controllers/application_controller.rb
  app/controllers/carts_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/products_controller.rb
  app/helpers/carts_helper.rb
  app/helpers/orders_helper.rb
  app/models/address.rb
  app/models/cart.rb
  app/models/line_item.rb
  app/models/order.rb
  app/models/order_item.rb
  app/models/product.rb
  app/models/user.rb
  app/views/carts/index.html.erb
  app/views/carts/show.html.erb
  app/views/orders/index.html.erb
  app/views/orders/show.html.erb
  app/views/partials/layout/_navbar.html.erb
  app/views/products/index.html.erb
  app/views/products/show.html.erb
  config/routes.rb
  db/migrate/20230816213514_create_carts.rb
  db/migrate/20230816213526_create_line_items.rb
  db/migrate/20230818155844_create_orders.rb
  db/migrate/20230818155911_create_order_items.rb
  db/schema.rb
  test/controllers/addresses_controller_test.rb
  test/controllers/carts_controller_test.rb
  test/controllers/orders_controller_test.rb
  test/fixtures/carts.yml
  test/fixtures/line_items.yml
  test/fixtures/order_items.yml
  test/fixtures/orders.yml
  test/models/address_test.rb
  test/models/admin_test.rb
  test/models/cart_test.rb
  test/models/customer_test.rb
  test/models/line_item_test.rb
  test/models/order_item_test.rb
  test/models/order_test.rb
  test/models/product_test.rb
Labels: WIP, review required

#33 Build home page
  Gemfile
  Gemfile.lock
  app/assets/images/CoheteBanner.webp
  app/assets/images/ElReyBanner.webp
  app/assets/images/FoodMoneyBanner.webp
  app/assets/images/Junior.webp
  app/assets/images/MonkeyAbout.webp
  app/assets/images/granadaBanner.webp
  app/assets/images/reyColoresBanner.webp
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/_banner.scss
  app/assets/stylesheets/components/_buttons.scss
  app/assets/stylesheets/components/_confirmation.scss
  app/assets/stylesheets/components/_home.scss
  app/assets/stylesheets/components/_links.scss
  app/assets/stylesheets/components/_login.scss
  app/assets/stylesheets/components/_passwords.scss
  app/assets/stylesheets/components/_products.scss
  app/assets/stylesheets/components/_registrations.scss
  app/assets/stylesheets/components/_top-message.scss
  app/assets/stylesheets/config/variables.scss
  app/assets/stylesheets/layout/_navbar.scss
  app/controllers/about_controller.rb
  app/controllers/faqs_controller.rb
  app/helpers/about_helper.rb
  app/helpers/faqs_helper.rb
  app/javascript/application.js
  app/javascript/jquery_ui.js
  app/javascript/navbar.js
  app/views/about/index.html.erb
  app/views/addresses/_form.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/faqs/index.html.erb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/partials/Banners/_CoheteBanner.html.erb
  app/views/partials/Banners/_ElReyBanner.html.erb
  app/views/partials/Banners/_FoodMoney.html.erb
  app/views/partials/Banners/_GranadaBanner.html.erb
  app/views/partials/Banners/_JuniorHBanner.html.erb
  app/views/partials/Banners/_ReyColoresBanner.html.erb
  app/views/partials/Products/_products.html.erb
  app/views/partials/layout/_footer.html.erb
  app/views/partials/layout/_navbar.html.erb
  config/importmap.rb
  config/initializers/assets.rb
  config/routes.rb
  test/controllers/about_controller_test.rb
  test/controllers/faqs_controller_test.rb
Labels: review required

#41 Improve shopping cart
  app/controllers/about_controller.rb
  app/controllers/application_controller.rb
  app/controllers/carts_controller.rb
  app/controllers/faqs_controller.rb
  app/controllers/products_controller.rb
  app/views/carts/index.html.erb
  app/views/partials/layout/_navbar.html.erb
  app/views/products/_product.html.erb
  config/routes.rb
Labels: review required

#45 Improve order
  app/controllers/adminorders_controller.rb
  app/controllers/carts_controller.rb
  app/helpers/adminorders_helper.rb
  app/models/order.rb
  app/models/user.rb
  app/views/adminorders/edit.html.erb
  app/views/adminorders/index.html.erb
  app/views/adminorders/show.html.erb
  app/views/orders/show.html.erb
  config/routes.rb
  db/migrate/20230825003110_add_status_to_orders.rb
  db/schema.rb
  test/controllers/adminorders_controller_test.rb
Labels: review required

#44 Shopping cart view
  app/views/carts/index.html.erb
  app/views/carts/show.html.erb
Labels: review required

#42 Fixed navbar styles
  app/assets/stylesheets/layout/_navbar.scss
  app/controllers/application_controller.rb
  app/views/partials/layout/_navbar.html.erb
Labels: review required
